=== harvard-lts/fits/xml/fits_output.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" targetNamespace="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="fits">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="statistics" type="statisticsType" minOccurs="0"/>
				<xs:element name="identification" type="identificationType" minOccurs="0"/>
				<xs:element name="fileinfo" type="fileInfoType" minOccurs="0"/>
				<xs:element name="filestatus" type="fileStatusType" minOccurs="0"/>
				<xs:element name="metadata" type="metadataType" minOccurs="0"/>
				<xs:element name="statistics" type="statisticsType" minOccurs="0"/>
				<xs:element name="toolOutput" type="toolOutputType" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="optional"/>
			<xs:attribute name="timestamp" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- Attribute Groups -->
	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SINGLE_RESULT"/>
			<xs:enumeration value="CONFLICT"/>
			<xs:enumeration value="PARTIAL"/>
			<xs:enumeration value="UNKNOWN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="nameVersionStatusAttrGrp">
		<xs:attributeGroup ref="nameVersionAttrGrp"/>
		<xs:attribute name="status" type="statusType" use="optional"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="nameVersionAttrGrp">
		<xs:attribute name="toolname" type="xs:string" use="optional"/>
		<xs:attribute name="toolversion" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<!-- FITS Metadata type -->
	<xs:complexType name="fitsMetadataType">
		<xs:complexContent>
			<xs:extension base="xs:anyType">
				<xs:attributeGroup ref="nameVersionStatusAttrGrp"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Statistics elements -->
	<xs:complexType name="statisticsType">
		<xs:sequence>
			<xs:element name="tool" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attributeGroup ref="nameVersionAttrGrp"/>
					<xs:attribute name="executionTime" type="xs:integer"/>
					<xs:attribute name="status" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="fitsExecutionTime" type="xs:integer"/>
	</xs:complexType>
	<!-- Identification elements-->
	<xs:complexType name="identificationType">
		<xs:sequence>
			<xs:element name="identity" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="tool" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="version" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="externalIdentifier" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="format" type="xs:string"/>
					<xs:attribute name="mimetype" type="xs:string"/>
					<xs:attribute name="toolname" type="xs:string" use="optional"/>
					<xs:attribute name="toolversion" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="status" type="statusType" use="optional"/>
	</xs:complexType>
	<xs:element name="tool">
		<xs:complexType>
			<xs:attributeGroup ref="nameVersionAttrGrp"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="version">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="nameVersionStatusAttrGrp"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="externalIdentifier">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="nameVersionAttrGrp"/>
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!--file info elements-->
	<xs:complexType name="fileInfoType">
		<xs:group ref="fileInfoElements" minOccurs="0" maxOccurs="unbounded"/>
	</xs:complexType>
	<xs:group name="fileInfoElements">
		<xs:choice>
			<xs:element name="filepath" type="fitsMetadataType"/>
			<xs:element name="filename" type="fitsMetadataType"/>
			<xs:element name="size" type="fitsMetadataType"/>
			<xs:element name="md5checksum" type="fitsMetadataType"/>
			<xs:element name="lastmodified" type="fitsMetadataType"/>
			<xs:element name="fslastmodified" type="fitsMetadataType"/>
			<xs:element name="created" type="fitsMetadataType"/>
			<xs:element name="creatingApplicationName" type="fitsMetadataType"/>
			<xs:element name="creatingApplicationVersion" type="fitsMetadataType"/>
			<xs:element name="inhibitorType" type="fitsMetadataType"/>
			<xs:element name="inhibitorTarget" type="fitsMetadataType"/>
			<xs:element name="rightsBasis" type="fitsMetadataType"/>
			<xs:element name="copyrightBasis" type="fitsMetadataType"/>
			<xs:element name="copyrightNote" type="fitsMetadataType"/>
			<xs:element name="creatingos" type="fitsMetadataType"/>
		</xs:choice>
	</xs:group>
	<!-- file status elements -->
	<xs:complexType name="fileStatusType">
		<xs:group ref="fileStatusElements" minOccurs="0" maxOccurs="unbounded"/>
	</xs:complexType>
	<xs:group name="fileStatusElements">
		<xs:choice>
			<xs:element name="well-formed" type="fitsMetadataType"/>
			<xs:element name="valid" type="fitsMetadataType"/>
			<xs:element name="message" type="fitsMetadataType"/>
		</xs:choice>
	</xs:group>
	<!-- metadata types -->
	<xs:complexType name="metadataType">
		<xs:choice>
			<xs:element name="image" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="text" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="document" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="audio" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="video" type="technicalMetadata" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="technicalMetadata">
		<xs:sequence>
			<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- tool output type -->
	<xs:complexType name="toolOutputType">
		<xs:sequence>
			<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== harvard-lts/fits/testfiles/output/epub30-test-font-embedding-obfuscation.epub_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output https://some-other-pid-service/fits_output.xsd" version="1.6.0-SNAPSHOT" timestamp="1/12/23, 8:26 PM">
  <identification>
    <identity format="EPUB" mimetype="application/epub+zip" toolname="FITS" toolversion="1.6.0-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.5.2" />
      <tool toolname="file utility" toolversion="5.43" />
      <tool toolname="Exiftool" toolversion="12.50" />
      <tool toolname="Tika" toolversion="2.6.0" />
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">fmt/483</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/fits/testfiles/input/epub30-test-font-embedding-obfuscation.epub</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">epub30-test-font-embedding-obfuscation.epub</filename>
    <size toolname="OIS File Information" toolversion="1.0">1176408</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">8fcf4ac8f3ba4670ff204b200d1a910e</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1667144388462</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <document>
      <title toolname="Exiftool" toolversion="12.50">EPUBTEST 0103 - Font Embedding and Obfuscation Tests</title>
      <author toolname="Exiftool" toolversion="12.50" status="SINGLE_RESULT">Markus Gylling, Vincent Gros, Toshiaki Koike, Marisa DeMeglio, Matt Garrish, Ori Idan</author>
      <isRightsManaged toolname="Exiftool" toolversion="12.50">yes</isRightsManaged>
      <description toolname="Exiftool" toolversion="12.50">Tests for Font Embedding and Obfuscation [UNDER CONSTRUCTION]</description>
      <identifier toolname="Exiftool" toolversion="12.50">com.github.epub-testsuite.epub30-test-0103</identifier>
      <language toolname="Exiftool" toolversion="12.50">en</language>
      <standard>
        <docmd:document xmlns:docmd="http://www.fcla.edu/docmd">
          <docmd:Language>en</docmd:Language>
        </docmd:document>
      </standard>
    </document>
  </metadata>
  <statistics fitsExecutionTime="963">
    <tool toolname="MediaInfo" toolversion="22.09" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.5.2" executionTime="101" />
    <tool toolname="jpylyzer" toolversion="2.1.0" status="did not run" />
    <tool toolname="Jhove" toolversion="1.26.1" status="did not run" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.43" executionTime="181" />
    <tool toolname="Exiftool" toolversion="12.50" executionTime="953" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="85" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="93" />
    <tool toolname="Tika" toolversion="2.6.0" executionTime="176" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/Doc2.rtf_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output https://some-other-pid-service/fits_output.xsd" version="1.6.0-SNAPSHOT" timestamp="1/12/23, 8:26 PM">
  <identification>
    <identity format="Rich Text Format (RTF)" mimetype="application/rtf" toolname="FITS" toolversion="1.6.0-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.5.2" />
      <tool toolname="file utility" toolversion="5.43" />
      <tool toolname="Exiftool" toolversion="12.50" />
      <tool toolname="Tika" toolversion="2.6.0" />
      <version toolname="Droid" toolversion="6.5.2">1.9</version>
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">fmt/355</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <lastmodified toolname="Exiftool" toolversion="12.50" status="SINGLE_RESULT">2015-09-24T12:17:00</lastmodified>
    <created toolname="Exiftool" toolversion="12.50" status="CONFLICT">2015-09-24T12:16:00</created>
    <created toolname="Tika" toolversion="2.6.0" status="CONFLICT">2015-09-24T16:16:00Z</created>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/fits/testfiles/input/Doc2.rtf</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">Doc2.rtf</filename>
    <size toolname="OIS File Information" toolversion="1.0">26328</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">26301ff11c920c4e32f9fa7d706390a6</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1667144387463</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <document>
      <pageCount toolname="Exiftool" toolversion="12.50">1</pageCount>
      <wordCount toolname="Exiftool" toolversion="12.50">0</wordCount>
      <characterCount toolname="Exiftool" toolversion="12.50">0</characterCount>
      <author toolname="Exiftool" toolversion="12.50">Aloisio, Paul G.</author>
      <standard>
        <docmd:document xmlns:docmd="http://www.fcla.edu/docmd">
          <docmd:PageCount>1</docmd:PageCount>
          <docmd:WordCount>0</docmd:WordCount>
          <docmd:CharacterCount>0</docmd:CharacterCount>
        </docmd:document>
      </standard>
    </document>
  </metadata>
  <statistics fitsExecutionTime="276">
    <tool toolname="MediaInfo" toolversion="22.09" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.5.2" executionTime="29" />
    <tool toolname="jpylyzer" toolversion="2.1.0" status="did not run" />
    <tool toolname="Jhove" toolversion="1.26.1" status="did not run" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.43" executionTime="123" />
    <tool toolname="Exiftool" toolversion="12.50" executionTime="266" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="53" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" status="did not run" />
    <tool toolname="Tika" toolversion="2.6.0" executionTime="51" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/MMS-82A.08.12.02.ai_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.2.0" timestamp="8/9/17 3:16 PM">
  <identification>
    <identity format="Adobe Illustrator" mimetype="application/postscript" toolname="FITS" toolversion="1.2.0">
      <tool toolname="Droid" toolversion="6.3" />
      <tool toolname="Exiftool" toolversion="10.00" />
      <version toolname="Droid" toolversion="6.3">9.0</version>
      <externalIdentifier toolname="Droid" toolversion="6.3" type="puid">fmt/558</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <size toolname="Jhove" toolversion="1.16">561633</size>
    <creatingApplicationName toolname="Jhove" toolversion="1.16">Adobe PDF library 4.800/Adobe Illustrator 9.0</creatingApplicationName>
    <created toolname="Exiftool" toolversion="10.00" status="SINGLE_RESULT">2002:08:10 18:43:47</created>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/git-daveneiman/fits/testfiles/MMS-82A.08.12.02.ai</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">MMS-82A.08.12.02.ai</filename>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">b09e1524642c0166da3566d4c7e03871</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1502306011000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <image>
      <imageWidth toolname="Exiftool" toolversion="10.00" status="SINGLE_RESULT">315</imageWidth>
      <imageHeight toolname="Exiftool" toolversion="10.00" status="SINGLE_RESULT">704</imageHeight>
    </image>
  </metadata>
  <statistics fitsExecutionTime="1716">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.3" executionTime="146" />
    <tool toolname="Jhove" toolversion="1.16" executionTime="665" />
    <tool toolname="file utility" toolversion="5.04" executionTime="557" />
    <tool toolname="Exiftool" toolversion="10.00" executionTime="624" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="141" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="487" />
    <tool toolname="Tika" toolversion="1.10" executionTime="1664" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/MacMSWORD_4-5.doc_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output https://some-other-pid-service/fits_output.xsd" version="1.6.0-SNAPSHOT" timestamp="1/12/23, 8:26 PM">
  <identification>
    <identity format="Microsoft Word Binary File Format" mimetype="application/msword" toolname="FITS" toolversion="1.6.0-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.5.2" />
      <tool toolname="file utility" toolversion="5.43" />
      <tool toolname="Tika" toolversion="2.6.0" />
      <version toolname="Droid" toolversion="6.5.2">4.0</version>
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">x-fmt/64</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/fits/testfiles/input/MacMSWORD_4-5.doc</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">MacMSWORD_4-5.doc</filename>
    <size toolname="OIS File Information" toolversion="1.0">2047</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">edc1036fd68b60ba62af22aa269fc0a8</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1667144387814</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata />
  <statistics fitsExecutionTime="421">
    <tool toolname="MediaInfo" toolversion="22.09" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.5.2" executionTime="39" />
    <tool toolname="jpylyzer" toolversion="2.1.0" status="did not run" />
    <tool toolname="Jhove" toolversion="1.26.1" status="did not run" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.43" executionTime="137" />
    <tool toolname="Exiftool" toolversion="12.50" executionTime="408" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" executionTime="357" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="27" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="56" />
    <tool toolname="Tika" toolversion="2.6.0" executionTime="41" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/simple_webvtt.vtt_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output https://some-other-pid-service/fits_output.xsd" version="1.6.0-SNAPSHOT" timestamp="1/12/23, 8:30 PM">
  <identification>
    <identity format="WebVTT" mimetype="text/vtt" toolname="FITS" toolversion="1.6.0-SNAPSHOT">
      <tool toolname="VTT Tool" toolversion="0.1" />
      <tool toolname="Droid" toolversion="6.5.2" />
      <tool toolname="file utility" toolversion="5.43" />
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">fmt/1454</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <size toolname="Jhove" toolversion="1.26.1">488</size>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/fits/testfiles/input/simple_webvtt.vtt</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">simple_webvtt.vtt</filename>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">6fd0c9caa00b08305344cc42244666af</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1667144388573</fslastmodified>
  </fileinfo>
  <filestatus>
    <well-formed toolname="Jhove" toolversion="1.26.1" status="SINGLE_RESULT">true</well-formed>
    <valid toolname="Jhove" toolversion="1.26.1" status="SINGLE_RESULT">true</valid>
  </filestatus>
  <metadata>
    <text>
      <linebreak toolname="Jhove" toolversion="1.26.1" status="SINGLE_RESULT">LF</linebreak>
      <charset toolname="Jhove" toolversion="1.26.1" status="SINGLE_RESULT">US-ASCII</charset>
      <standard>
        <textMD:textMD xmlns:textMD="info:lc/xmlns/textMD-v3">
          <textMD:character_info>
            <textMD:charset>US-ASCII</textMD:charset>
            <textMD:linebreak>LF</textMD:linebreak>
          </textMD:character_info>
        </textMD:textMD>
      </standard>
    </text>
  </metadata>
  <statistics fitsExecutionTime="355">
    <tool toolname="MediaInfo" toolversion="22.09" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" executionTime="55" />
    <tool toolname="Droid" toolversion="6.5.2" executionTime="312" />
    <tool toolname="jpylyzer" toolversion="2.1.0" status="did not run" />
    <tool toolname="Jhove" toolversion="1.26.1" executionTime="348" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.43" executionTime="165" />
    <tool toolname="Exiftool" toolversion="12.50" status="did not run" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="66" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="137" />
    <tool toolname="Tika" toolversion="2.6.0" status="did not run" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/32044020597662.zip_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.5.0-SNAPSHOT" timestamp="7/10/19 9:19 AM">
  <identification>
    <identity format="ZIP Format" mimetype="application/zip" toolname="FITS" toolversion="1.5.0-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.4" />
      <tool toolname="file utility" toolversion="5.31" />
      <tool toolname="Exiftool" toolversion="11.54" />
      <tool toolname="ffident" toolversion="0.2" />
      <tool toolname="Tika" toolversion="1.21" />
      <version toolname="file utility" toolversion="5.31">1.0</version>
      <externalIdentifier toolname="Droid" toolversion="6.4" type="puid">x-fmt/263</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/git-daveneiman/fits/testfiles/32044020597662.zip</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">32044020597662.zip</filename>
    <size toolname="OIS File Information" toolversion="0.2">95270</size>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">7c64750915af83a39c35f0e836d3690f</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1516117982000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <container>
      <originalSize toolname="Droid" toolversion="6.4" status="SINGLE_RESULT">83996</originalSize>
      <compressionMethod toolname="Droid" toolversion="6.4" status="SINGLE_RESULT">stored</compressionMethod>
      <entries totalEntries="84" toolname="Droid" toolversion="6.4" status="SINGLE_RESULT">
        <format name="Hypertext Markup Language" number="1" />
        <format name="JPEG 2000 JP2" number="40" />
        <format name="MD5 File" number="1" />
        <format name="Plain text" number="42" />
      </entries>
    </container>
  </metadata>
  <statistics fitsExecutionTime="556">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.4" executionTime="122" />
    <tool toolname="Jhove" toolversion="1.20.1" status="did not run" />
    <tool toolname="file utility" toolversion="5.31" executionTime="551" />
    <tool toolname="Exiftool" toolversion="11.54" executionTime="538" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="26" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="31" />
    <tool toolname="Tika" toolversion="1.21" executionTime="534" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/WordPerfect4_2.wp_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output https://some-other-pid-service/fits_output.xsd" version="1.6.0-SNAPSHOT" timestamp="1/12/23, 8:26 PM">
  <identification status="SINGLE_RESULT">
    <identity format="WordPerfect Document" mimetype="application/vnd.wordperfect" toolname="FITS" toolversion="1.6.0-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.5.2" />
      <version toolname="Droid" toolversion="6.5.2" status="CONFLICT">5.2</version>
      <version toolname="Droid" toolversion="6.5.2" status="CONFLICT">6 onwards</version>
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">x-fmt/203</externalIdentifier>
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">fmt/892</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/fits/testfiles/input/WordPerfect4_2.wp</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">WordPerfect4_2.wp</filename>
    <size toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">2677</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">a83edcaa67ad6338bbfee877815df532</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1667144388044</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata />
  <statistics fitsExecutionTime="628">
    <tool toolname="MediaInfo" toolversion="22.09" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.5.2" executionTime="75" />
    <tool toolname="jpylyzer" toolversion="2.1.0" status="did not run" />
    <tool toolname="Jhove" toolversion="1.26.1" status="did not run" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.43" executionTime="172" />
    <tool toolname="Exiftool" toolversion="12.76" status="did not run" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" executionTime="617" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="88" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="98" />
    <tool toolname="Tika" toolversion="2.6.0" executionTime="76" />
  </statistics>
</fits>
